#!/bin/bash
if [[ -z $1 ]]; then 
    echo "[ERROR] File path must be passed" 1>&2
    exit 1
fi

file="${1}"
while IFS= read -r line
do
    # display $line or do somthing with $line
	printf '%s\n' "$line"
done <"$file"
